# Generated by Django 3.0.5 on 2020-05-17 01:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airbnb', '0002_auto_20200516_1421'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accommodation',
            new_name='Home',
        ),
    ]
