# Generated by Django 3.0.5 on 2020-05-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0003_auto_20200516_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
