# Generated by Django 3.0.5 on 2020-05-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0005_auto_20200516_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image',
            field=models.FileField(default="{% static 'img/estadia.jpeg' %}", upload_to='media/'),
        ),
    ]
