# Generated by Django 3.0.5 on 2020-05-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0006_home_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='creation_date',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.FileField(default='img/estadia.jpeg', upload_to='%Y/%m/%d/'),
        ),
    ]
