# Generated by Django 3.0.5 on 2020-05-18 19:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0008_auto_20200518_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='airbnb.Home')),
            ],
        ),
    ]
