# Generated by Django 3.0.5 on 2020-05-19 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0010_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='created',
            new_name='rated_on',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='vote',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='updated',
        ),
    ]
