# Generated by Django 3.0.5 on 2020-05-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0014_auto_20200519_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='city',
            field=models.CharField(default='Cidade não informada', max_length=200),
        ),
        migrations.AddField(
            model_name='home',
            name='state',
            field=models.CharField(default='Estado não informado', max_length=200),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
