# Generated by Django 3.0.5 on 2020-05-21 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0016_auto_20200521_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='home',
        ),
        migrations.AddField(
            model_name='home',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airbnb.Address'),
        ),
    ]
