# Generated by Django 3.0.5 on 2020-05-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0017_auto_20200521_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
