# Generated by Django 3.0.5 on 2020-05-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0019_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='total_value',
            field=models.IntegerField(default=0),
        ),
    ]
