# Generated by Django 3.0.5 on 2020-05-23 22:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0023_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
