# Generated by Django 3.0.5 on 2020-05-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0025_auto_20200523_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(default='media/1.jpg', upload_to='media/', verbose_name='Fotografia'),
        ),
    ]
